server:
  port: 9001
  servlet:
    context-path: /desafio

spring:
  application:
    name: desafio-hyperativa-backend
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  jpa:
    hibernate.ddl-auto: create
    open-in-view: true 
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB

app:
  security:
    aes-key: "Y2hhdmVleGVtcGxvY2hhdmVleGVtcGxvMDEyMzQ1Njc="
  
logging:
  file:
    path: ./
  level:
    root: INFO
    '[br.com.cesarfjr]': DEBUG
    org.springframework.security: TRACE
  
