server:
  port: ${SERVER_PORT:9001}
  servlet:
    context-path: /desafio

spring:
  application:
    name: desafio-hyperativa-backend
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER:org.hsqldb.jdbc.JDBCDriver}
    url: ${DATASOURCE_URL:jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    open-in-view: true 
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB
  jackson:
    default-property-inclusion: NON_NULL
    
app:
  security:
    aes-key: "Y2hhdmVleGVtcGxvY2hhdmVleGVtcGxvMDEyMzQ1Njc="
  jwt:
    key: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA # according to SHA-256 requirements
    algorithm: HS256
    issuer: http://localhost:9001
    expiresIn: 60m

logbook:
  format:
    style: json
  filter:
    enabled: true

logging:
  file:
    path: ${LOG_PATH:./}
  level:
    root: WARN
    '[br.com.cesarfjr]': DEBUG  
    '[org.zalando.logbook.Logbook]': TRACE